export const bares = [
  {
    id: 'bar_001',
    nombre: "Rosella's Bar",
    email: 'jack@rosellasbar.com.au',
    direccion: '1734 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0847,
    lng: 153.4498,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_002',
    nombre: 'Sueno Rooftop Bar',
    email: 'seatme@norte.restaurant',
    direccion: '2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0490,
    lng: 153.4375,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_003',
    nombre: 'Familiar Spirits',
    email: 'sales@familiarspirits.com.au',
    direccion: '1/9 Calabro Way, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0861,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_004',
    nombre: 'Bar Monte',
    email: 'miami@barmonte.com.au',
    direccion: '3 Mountain View Ave, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0720,
    lng: 153.4470,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_005',
    nombre: 'Burly Bar',
    email: 'hello@burlygin.com',
    direccion: '60 Currumbin Creek Rd, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1538,
    lng: 153.4720,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_006',
    nombre: 'JuJu Mermaid Beach',
    email: 'hello@jujumermaidbeach.com.au',
    direccion: '2235 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0510,
    lng: 153.4380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_007',
    nombre: 'Paloma Wine Bar',
    email: 'hello@palomawinebar.com',
    direccion: '1/12 James St, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0855,
    lng: 153.4505,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_008',
    nombre: 'Lars Bar & Grill',
    email: 'info@larsbarandgrill.com.au',
    direccion: 'Shop 1, 2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0495,
    lng: 153.4376,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_009',
    nombre: 'Hyde Paradiso',
    email: 'reservations@hydeparadiso.com',
    direccion: 'Level 2/8 The Esplanade, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0026,
    lng: 153.4296,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_010',
    nombre: 'Aviary Rooftop Bar',
    email: 'bookings.coordinator@southportsharks.com.au',
    direccion: 'Cnr Olsen & Musgrave Ave, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9672,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_011',
    nombre: 'Garden Kitchen & Bar',
    email: 'dining@star.com.au',
    direccion: 'Casino Level, The Star Gold Coast, 1 Casino Dr, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0343,
    lng: 153.4330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_012',
    nombre: "Mr. PP's Rooftop",
    email: 'hello@mrpp.com.au',
    direccion: '43 Nerang St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9680,
    lng: 153.3990,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_013',
    nombre: 'The Island Rooftop',
    email: 'stay@theislandgoldcoast.com.au',
    direccion: '3128 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0024,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_014',
    nombre: 'The Exhibitionist Bar',
    email: 'theexhibitionistbar@experiencegoldcoast.com',
    direccion: 'Level 5, HOTA, 135 Bundall Rd, Surfers Paradise QLD 4217',
    barrio: 'Bundall',
    lat: -28.0175,
    lng: 153.4115,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_015',
    nombre: 'Nineteen at the Star',
    email: '',
    direccion: 'Level 19, The Darling, 1 Casino Dr, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0345,
    lng: 153.4332,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_016',
    nombre: 'The Cambus Wallace',
    email: '',
    direccion: '4/2237 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0515,
    lng: 153.4382,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_017',
    nombre: "Grandad Jack's Craft Distillery",
    email: 'goldcoast@granddadjacks.com',
    direccion: '45 Lemana Ln, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0730,
    lng: 153.4465,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_018',
    nombre: 'Burleigh Pavilion',
    email: 'managers@burleighpavilion.com',
    direccion: '3a/43 Goodwin Terrace, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0870,
    lng: 153.4515,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_019',
    nombre: 'Lockwood Bar',
    email: '',
    direccion: '7B Justin Ln, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0852,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_020',
    nombre: 'Justin Lane Rooftop',
    email: 'eat@justinlane.com.au',
    direccion: '1708-1710 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0840,
    lng: 153.4492,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_021',
    nombre: 'Destino Wine Bar',
    email: '',
    direccion: '4601 Masthead Way, Hope Island QLD 4212',
    barrio: 'Hope Island',
    lat: -27.8672,
    lng: 153.3680,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_022',
    nombre: 'Balter Taproom',
    email: 'functions@balter.com.au',
    direccion: '14 Traders Way, Currumbin Waters QLD 4223',
    barrio: 'Currumbin Waters',
    lat: -28.1487,
    lng: 153.4692,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_023',
    nombre: 'Kirra Beach House',
    email: '',
    direccion: '4 Marine Pde, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1673,
    lng: 153.5340,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_024',
    nombre: 'Apres Surf Bar',
    email: '',
    direccion: 'Shop 1, 1837 Gold Coast Hwy, Burleigh QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0832,
    lng: 153.4488,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_025',
    nombre: 'Hard Fizz Taproom',
    email: 'hello@getfizzy.co',
    direccion: '16 Hibiscus Haven, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0865,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_026',
    nombre: 'Southport Pavilion',
    email: 'management@southportpavilion.com.au',
    direccion: '2 Barney St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9660,
    lng: 153.3987,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_027',
    nombre: 'The Malibu Racquet Club',
    email: '',
    direccion: '1740 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0843,
    lng: 153.4494,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_028',
    nombre: 'Las Palmas Bar & Restaurant',
    email: 'hello@laspalmas.com.au',
    direccion: '1097 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1172,
    lng: 153.4660,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_029',
    nombre: 'Suga Rum Bar',
    email: 'suga.palmbeach@gmail.com',
    direccion: '1142 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1180,
    lng: 153.4665,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_030',
    nombre: 'Lulu Rooftop Bar',
    email: 'info@lulurooftopbar.com.au',
    direccion: 'Level 2, 4 Orchid Avenue, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0032,
    lng: 153.4305,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_031',
    nombre: 'Sandbar Gold Coast',
    email: 'info@sandbargc.com',
    direccion: '52 Esplanade, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4302,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_032',
    nombre: "Hurricane's Grill & Bar Surfers Paradise",
    email: '',
    direccion: 'Cavill Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0030,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_033',
    nombre: 'BLVD Cafe & Bar',
    email: '',
    direccion: 'Cnr Surfers Paradise Blvd & Hanlan St, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0028,
    lng: 153.4294,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_034',
    nombre: 'Steampunk Surfers Paradise',
    email: 'admin@elstonvenues.com.au',
    direccion: 'L1 3113 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0036,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_035',
    nombre: 'Soho House Bar',
    email: '',
    direccion: '4/2713 Gold Coast Hwy, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0340,
    lng: 153.4335,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_036',
    nombre: 'Bruce Currumbin',
    email: '',
    direccion: 'Shop 1/794 Pacific Pde, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1542,
    lng: 153.4725,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_037',
    nombre: 'Moustache Wine Bar',
    email: '',
    direccion: '3/2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0492,
    lng: 153.4377,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_038',
    nombre: 'Kirra Beach Hotel',
    email: 'jcraig@kirrabeachhotel.com.au',
    direccion: '4 Marine Pde, Kirra QLD 4225',
    barrio: 'Kirra',
    lat: -28.1668,
    lng: 153.5330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_039',
    nombre: 'The Tropic Bar Burleigh',
    email: 'reservations@burleighpavilion.com',
    direccion: '1 Goodwin Terrace, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0872,
    lng: 153.4518,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_040',
    nombre: 'Stables Bar & Kitchen',
    email: '',
    direccion: '4 Freshwater St, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0858,
    lng: 153.4500,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_041',
    nombre: 'Currumbin Creek Tavern',
    email: 'info@currumbinhotel.com',
    direccion: '2172 Gold Coast Hwy, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0710,
    lng: 153.4460,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_042',
    nombre: 'The Collective Palm Beach',
    email: '',
    direccion: '1071 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1165,
    lng: 153.4656,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_043',
    nombre: "Kurrawa Surf Club Bar",
    email: 'info@kurrawasurf.com.au',
    direccion: 'Old Burleigh Rd, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0350,
    lng: 153.4340,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_044',
    nombre: 'Glass Dining & Lounge Bar',
    email: '',
    direccion: '71 Seaworld Dr, Main Beach QLD 4217',
    barrio: 'Main Beach',
    lat: -27.9770,
    lng: 153.4100,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_045',
    nombre: 'The Pink Hotel Coolangatta',
    email: 'frontdesk@thepinkhotelcoolangatta.com',
    direccion: '171 Griffith St, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1660,
    lng: 153.5345,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_046',
    nombre: "Mano's Tedde Rave",
    email: 'info@manostedderave.com.au',
    direccion: '19-21 Tedder Ave, Main Beach QLD 4217',
    barrio: 'Main Beach',
    lat: -27.9772,
    lng: 153.4105,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_047',
    nombre: 'The Coolangatta Hotel',
    email: '',
    direccion: 'Cnr Warner St & Marine Pde, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1672,
    lng: 153.5342,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_048',
    nombre: 'Coolangatta Sands Hotel',
    email: 'manager@coolangattasandshotel.com.au',
    direccion: 'Cnr Griffith & McLean Sts, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1668,
    lng: 153.5348,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_049',
    nombre: 'BOTH Espresso and Wine',
    email: 'info@bothespressoandwine.com.au',
    direccion: '12/128 Lae Dr, Runaway Bay QLD 4216',
    barrio: 'Hope Island',
    lat: -27.8965,
    lng: 153.3905,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Cafe de dia, wine bar de tarde. Apertura 2025.',
  },
  {
    id: 'bar_050',
    nombre: 'The Hearth Cafe & Providore',
    email: 'hello@thehearth.au',
    direccion: '53 Hardys Rd, Mudgeeraba QLD 4213',
    barrio: 'Robina',
    lat: -28.0900,
    lng: 153.3650,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Cafe y tienda de productos artesanales. Abre mie-dom. Apertura 2025.',
  },
  {
    id: 'bar_051',
    nombre: 'Hotel Jardin',
    email: 'hello@hoteljardin.com.au',
    direccion: '3240 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0040,
    lng: 153.4305,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Lobby Bar, Piano Bar y SABA Kitchen. Tel: 07 5662 1300. Apertura 2025.',
  },
  {
    id: 'bar_052',
    nombre: 'BSKT Cafe Nobby Beach',
    email: 'hello@bskt.com.au',
    direccion: 'Cnr Jesse St & Gold Coast Hwy, Nobby Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0580,
    lng: 153.4395,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Cafe todo el dia, desayuno y almuerzo. Muy popular en la zona.',
  },
  {
    id: 'bar_053',
    nombre: 'Fire Baby',
    email: '',
    direccion: '10 Welch St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9710,
    lng: 153.3980,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Pizzeria italiana y cocina al fuego (Ember). Tel: (07) 5577 4429.',
  },
  {
    id: 'bar_054',
    nombre: 'River House',
    email: 'fox@riverhouse4215.com.au',
    direccion: '2 Barney St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9660,
    lng: 153.3987,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fine dining frente al rio Nerang. Chef Grant Madgwick. Apertura 2025.',
  },
  {
    id: 'bar_055',
    nombre: 'Costa Taco Burleigh Heads',
    email: 'events@costa-taco.com',
    direccion: '1718 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0838,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: true,
    notas: 'Duplicado de bar_065. Taqueria mexicana. Hermanos Matt y Nick Stanley. Apertura oct 2025.',
  },
  {
    id: 'bar_056',
    nombre: 'BabyMama by Mamasan',
    email: 'eat@babymama.com.au',
    direccion: '2/2243 Gold Coast Hwy, Nobby Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0510,
    lng: 153.4380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Restaurante East Asian de los duenos de Mamasan. Tel: 0468 912 708.',
  },
  {
    id: 'bar_057',
    nombre: 'Tarte Bakery & Cafe',
    email: 'work@tarte.com.au',
    direccion: '2 West St, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0862,
    lng: 153.4505,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Bakery y cafe. Sin reservas. Multiples locales en GC incluyendo Tarte Tea Garden en Currumbin.',
  },
  {
    id: 'bar_058',
    nombre: 'Velvet Cafe & Lounge',
    email: 'hello@velvetcafelounge.com.au',
    direccion: '3 Ozone Parade, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0728,
    lng: 153.4462,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Cafe y wine bar. Apertura diciembre 2025. Creado por Stefany Rincon y John Potter.',
  },
  {
    id: 'bar_059',
    nombre: 'Meltemi Mediterrania',
    email: 'info@meltemi.com.au',
    direccion: '17 Albert Ave, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0338,
    lng: 153.4328,
    status: 'Pendiente',
    emailVerified: null,
    hidden: true,
    notas: 'Duplicado de bar_066. Restaurante mediterraneo. Chef Tapos Singha. Tel: 07 5620 2522. Apertura 2025.',
  },
  {
    id: 'bar_060',
    nombre: 'Padre Brewing Co.',
    email: '',
    direccion: '9 Ozone Parade, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0725,
    lng: 153.4460,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Cerveceria artesanal local. 160 asientos. Apertura 2025.',
  },
  {
    id: 'bar_061',
    nombre: 'Mamasan Kitchen & Bar',
    email: 'eat@mamasanbroadbeach.com',
    direccion: '3 Oracle Blvd, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0348,
    lng: 153.4332,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Restaurante asiatico. Tel: (07) 5527 5700.',
  },
  {
    id: 'bar_062',
    nombre: "Fig 'n' Fox",
    email: 'hello@fignfox.au',
    direccion: 'Shop 10/2 Elkhorn Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0023,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Pub ingles de dos pisos. Timmy\'s Tea Room en subsuelo. Musica en vivo. Tel: 07 5619 8177.',
  },
  {
    id: 'bar_063',
    nombre: 'LiTO Burleigh Heads',
    email: 'goldcoast.lito@mondrianhotels.com',
    direccion: 'Ground Level, 3 First Ave, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0867,
    lng: 153.4512,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Restaurante italiano todo el dia en la planta baja del Mondrian Gold Coast.',
  },
  {
    id: 'bar_064',
    nombre: 'Hotel Jardin',
    email: 'hello@hoteljardin.com.au',
    direccion: 'Chevron Renaissance, 3240 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4288,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar y restaurante en Chevron Renaissance. Lobby Bar, Piano Bar, SABA Kitchen. Tel: 07 5662 1300.',
  },
  {
    id: 'bar_065',
    nombre: 'Costa Taco Burleigh Heads',
    email: 'events@costa-taco.com',
    direccion: 'Shop 1-2, 1718 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0872,
    lng: 153.4508,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Mexicano premium. Sin reservas, walk-in. Tienen ubicaciones en Broadbeach y Byron Bay tambien.',
  },
  {
    id: 'bar_066',
    nombre: 'Meltemi Mediterrania',
    email: 'info@meltemi.com.au',
    direccion: '17 Albert Ave, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0345,
    lng: 153.4328,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Restaurante mediterraneo. Abre Wed-Sun. Tel: 07 5620 2522.',
  },
  {
    id: 'bar_067',
    nombre: 'Paradox Coffee Roasters Cafe',
    email: 'cafegc@paradoxroasters.com',
    direccion: '4 Charles Ave, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0350,
    lng: 153.4325,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Cafe de especialidad en The Oracle Boulevard. Lun-Dom 5:30am - 2:30pm. Tel: 0408 539 039.',
  },
  {
    id: 'bar_068',
    nombre: 'Currumbin RSL',
    email: 'reception@currumbinrsl.com.au',
    direccion: '165 Duringan Street, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1578,
    lng: 153.4668,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Club RSL grande con bar, restaurante La Bocca, gaming y Soundlounge. Tel: 07 5534 7999.',
  },
  {
    id: 'bar_069',
    nombre: 'Cooly Breeze Rooftop',
    email: 'info@coolybreezerooftop.com',
    direccion: '122 Griffith St Level 13, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1690,
    lng: 153.5406,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar y restaurante mediterraneo en terraza del piso 13. Vistas al mar. Tel: 07 4801 7363 / 0434 107 559.',
  },
  {
    id: 'bar_070',
    nombre: 'Baskk Italian Coolangatta',
    email: 'request@baskk.co',
    direccion: '52-58 Marine Parade, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1680,
    lng: 153.5398,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Restaurante y bar italiano frente a la playa de Kirra Point. Tel: 0478 967 407.',
  },
  {
    id: 'bar_071',
    nombre: 'Coolangatta Surf Club',
    email: 'reception@coolangattasurfclub.com',
    direccion: 'Cnr Dutton St & Marine Pde, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1692,
    lng: 153.5415,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar, bistro y cafe Board Short Barista. Abre 7 dias desde las 11am. No requiere reservas. Tel: 07 5536 4648.',
  },
  {
    id: 'bar_072',
    nombre: 'Bar Ricci Main Beach',
    email: 'info@barricci.com.au',
    direccion: '20 Tedder Avenue, Main Beach QLD 4217',
    barrio: 'Main Beach',
    lat: -27.9728,
    lng: 153.4258,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar y restaurante italiano. Dining Room y Wine Bar. Apertura 2026. Tel: 07 5528 4286. Mar-Dom desde mediodia.',
  },
  {
    id: 'bar_073',
    nombre: 'Greenmount Beach Surf Club',
    email: 'functions@greenmountsurfclub.com.au',
    direccion: 'Cnr Hill Street & Marine Parade, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1695,
    lng: 153.5418,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Surf club con bar y restaurant frente al mar. Eventos y funciones. Manager: manager@greenmountsurfclub.com.au',
  },
  {
    id: 'bar_074',
    nombre: 'Kaktus Bar (Southport Sharks)',
    email: 'bookings.coordinator@southportsharks.com.au',
    direccion: 'Cnr Olsen & Musgrave Ave, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9690,
    lng: 153.3970,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar mexicano en el club Southport Sharks. Margaritas, tequila y tacos. +18 despues de las 7pm. Mie-Jue 5pm-10pm, Vie 5pm-late, Sab 12pm-late, Dom 11am-5pm. Tel: 07 5532 1155.',
  },
  {
    id: 'bar_075',
    nombre: 'Rumi Persian Restaurant Broadbeach',
    email: 'info@rumipersianrestaurant.com.au',
    direccion: '8/90 Surf Parade, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0345,
    lng: 153.4340,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Cocina persa. Compartir platos, cocteles y vinos. Abre Lun-Dom 12pm-9pm. Tel: 07 5511 4002. Sister venue: Sage Restaurant.',
  },
  {
    id: 'bar_076',
    nombre: 'Rumi Persian Restaurant Surfers Paradise',
    email: 'surfers@rumipersianrestaurant.com.au',
    direccion: '3240 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0018,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Segunda ubicacion de Rumi. Cocina persa. Chevron Renaissance. Tel: 07 2141 6518.',
  },
  {
    id: 'bar_077',
    nombre: 'Rowdy Ranch Steakhouse',
    email: 'hello@rowdyranch.com.au',
    direccion: '3/15 Orchid Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0015,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Steakhouse estilo honky-tonk. Toro mecanico, musica en vivo y DJs. Apertura 2026. Tel: 07 5224 2000. Lun-Mar 2pm-3am, Mie-Sab 11:30am-3am, Dom 2pm-3am.',
  },
  {
    id: 'bar_079',
    nombre: 'Backbone Bar Tugun',
    email: 'info@backbonebar.com',
    direccion: 'Shop 9, 489 Gold Coast Hwy, Tugun QLD 4224',
    barrio: 'Tugun',
    lat: -28.1417,
    lng: 153.4902,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bar casual familiar. Cervezas artesanales, comida asiatica, gelato y fish & chips. ABN: 53 632 808 907. Tel: 0467 649 202. Mar-Dom 11am-late.',
  },
  {
    id: 'bar_078',
    nombre: 'Hotel Jardin Surfers Paradise',
    email: 'hello@hoteljardin.com.au',
    direccion: 'Chevron Renaissance, 3240 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0015,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Venue multi-piso: SABA Restaurant (Pan-Asian, chef Minh Le), Bar casual PB y Piano Bar Level 1. Rooftop en apertura 2026. Tel: 07 5662 1300.',
  },
  {
    id: 'bar_080',
    nombre: 'Hope Island Tavern',
    email: 'info@hopeislandtavern.com.au',
    direccion: '93 Broadwater Ave, Hope Island QLD 4212',
    barrio: 'Hope Island',
    lat: -27.8775,
    lng: 153.3638,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Sports bar y restaurant. Parte de Aus Venue Co. Bistro Lun-Jue 11:30am-8:30pm, Vie-Sab 11am-9pm, Dom 11am-8:30pm. Gaming Lun-Dom 10am-4am. Tel: (07) 3558 3308.',
  },
  {
    id: 'bar_081',
    nombre: 'The Wattle Hotel',
    email: 'enquiries@thewattlehotel.com.au',
    direccion: '1 Reserve Road, Upper Coomera QLD 4209',
    barrio: 'Upper Coomera',
    lat: -27.8688,
    lng: 153.2944,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Pub & Bistro con live music, trivia y karaoke. Redcape Hotel Group. Bistro Lun-Dom 11:30am-2:30pm y 5pm-8:30pm. Hotel Lun-Sab 10am-2:30am, Dom 10am-12:30am. Tel: (07) 5500 0700.',
  },
  {
    id: 'bar_082',
    nombre: 'Coomera Tavern',
    email: 'coomeratavern@alhgroup.com.au',
    direccion: '2 City Centre Drive, Upper Coomera QLD 4209',
    barrio: 'Upper Coomera',
    lat: -27.8580,
    lng: 153.3310,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Bistro y Sports Bar. ALH Group. Everyday 10am-4am. Bistro Lun-Jue 11:30am-2:30pm y 5:30pm-8:30pm, Vie-Dom 11:30am-8:30pm. Tel: (07) 5665 8033.',
  },
  {
    id: 'bar_083',
    nombre: 'Gold Coast Tavern',
    email: 'info@goldcoasttavern.com.au',
    direccion: '150 Bundall Rd, Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0002,
    lng: 153.4140,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Pub & bistro en Bundall. Dom-Mie 10am-late, Jue-Sab 10am-2am. Bistro Lun-Jue 11:30am-3pm y 5:30pm-9pm, Vie 11:30am-9:30pm, Sab 11:30am-3pm y 5:30pm-9:30pm, Dom 11:30am-9pm. Tel: (07) 5500 0214.',
  },
  {
    id: 'bar_084',
    nombre: 'Currumbin RSL',
    email: 'reception@currumbinrsl.com.au',
    direccion: '165 Duringan Street, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1640,
    lng: 153.4645,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Club RSL con bar, bistro, gaming, SoundLounge (venue ticketed), sports bar y La Bocca Pizza. Tel: 07 5534 7999. Tambien: dining@currumbinrsl.com.au (para dining/funciones).',
  },
  {
    id: 'bar_085',
    nombre: 'Balter Brewing Company',
    email: 'hello@balter.com.au',
    direccion: '14 Traders Way, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1426,
    lng: 153.4703,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Cerveceria artesanal y taproom. Fundada por surfistas. Parte de Asahi. Tel general: (07) 5518 8670 / Taproom: (07) 5525 6916. Tambien: events@balter.com.au (funciones), sales@balter.com.au.',
  },
  {
    id: 'bar_086',
    nombre: 'Palm Beach Hotel',
    email: 'palm.beach.hotel@alhgroup.com.au',
    direccion: 'Cnr 1118 Gold Coast Hwy & 5th Ave, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1260,
    lng: 153.4670,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Pub & bistro con accommodation. ALH Group / Nightcap Hotels. Everyday 10am-4am. Tel: (07) 5534 2188.',
  },
];
