export const bares = [
  {
    id: 'bar_001',
    nombre: "Rosella's Bar",
    email: 'jack@rosellasbar.com.au',
    direccion: '1734 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0847,
    lng: 153.4498,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_002',
    nombre: 'Sueno Rooftop Bar',
    email: 'hello@norte.restaurant',
    direccion: '2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0490,
    lng: 153.4375,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_003',
    nombre: 'Familiar Spirits',
    email: 'sales@familiarspirits.com.au',
    direccion: '1/9 Calabro Way, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0861,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_004',
    nombre: 'Bar Monte',
    email: 'info@barmonte.com.au',
    direccion: '3 Mountain View Ave, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0720,
    lng: 153.4470,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_005',
    nombre: 'Burly Bar',
    email: 'hello@burlygin.com',
    direccion: '60 Currumbin Creek Rd, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1538,
    lng: 153.4720,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_006',
    nombre: 'JuJu Mermaid Beach',
    email: 'bookings@jujumermaidbeach.com.au',
    direccion: '2235 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0510,
    lng: 153.4380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_007',
    nombre: 'Paloma Wine Bar',
    email: 'hello@palomawinebar.com',
    direccion: '1/12 James St, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0855,
    lng: 153.4505,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_008',
    nombre: 'Lars Bar & Grill',
    email: 'info@larsbarandgrill.com.au',
    direccion: 'Shop 1, 2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0495,
    lng: 153.4376,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_009',
    nombre: 'Hyde Paradiso',
    email: 'reservations@hydeparadiso.com',
    direccion: 'Level 2/8 The Esplanade, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0026,
    lng: 153.4296,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_010',
    nombre: 'Aviary Rooftop Bar',
    email: 'bookings.coordinator@southportsharks.com.au',
    direccion: 'Cnr Olsen & Musgrave Ave, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9672,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_011',
    nombre: 'Garden Kitchen & Bar',
    email: 'dining@star.com.au',
    direccion: 'Casino Level, The Star Gold Coast, 1 Casino Dr, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0343,
    lng: 153.4330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_012',
    nombre: "Mr. PP's Rooftop",
    email: 'hello@mrpp.com.au',
    direccion: '43 Nerang St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9680,
    lng: 153.3990,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_013',
    nombre: 'The Island Rooftop',
    email: 'stay@theislandgoldcoast.com.au',
    direccion: '3128 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0024,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_014',
    nombre: 'The Exhibitionist Bar',
    email: 'theexhibitionistbar@experiencegoldcoast.com',
    direccion: 'Level 5, HOTA, 135 Bundall Rd, Surfers Paradise QLD 4217',
    barrio: 'Bundall',
    lat: -28.0175,
    lng: 153.4115,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_015',
    nombre: 'Nineteen at the Star',
    email: 'nineteen@star.com.au',
    direccion: 'Level 19, The Darling, 1 Casino Dr, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0345,
    lng: 153.4332,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_016',
    nombre: 'The Cambus Wallace',
    email: 'hello@cambuswallace.com.au',
    direccion: '4/2237 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0515,
    lng: 153.4382,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_017',
    nombre: "Grandad Jack's Craft Distillery",
    email: 'goldcoast@granddadjacks.com',
    direccion: '45 Lemana Ln, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0730,
    lng: 153.4465,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_018',
    nombre: 'Burleigh Pavilion',
    email: 'managers@burleighpavilion.com',
    direccion: '3a/43 Goodwin Terrace, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0870,
    lng: 153.4515,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_019',
    nombre: 'Lockwood Bar',
    email: 'info@lockwood.bar',
    direccion: '7B Justin Ln, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0852,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_020',
    nombre: 'Justin Lane Rooftop',
    email: 'eat@justinlane.com.au',
    direccion: '1708-1710 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0840,
    lng: 153.4492,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_021',
    nombre: 'Destino Wine Bar',
    email: 'info@destino.com.au',
    direccion: '4601 Masthead Way, Hope Island QLD 4212',
    barrio: 'Hope Island',
    lat: -27.8672,
    lng: 153.3680,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_022',
    nombre: 'Balter Taproom',
    email: 'hello@balter.com.au',
    direccion: '14 Traders Way, Currumbin Waters QLD 4223',
    barrio: 'Currumbin Waters',
    lat: -28.1487,
    lng: 153.4692,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_023',
    nombre: 'Kirra Beach House',
    email: 'info@kirrabeachhouse.com',
    direccion: '4 Marine Pde, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1673,
    lng: 153.5340,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_024',
    nombre: 'Apres Surf Bar',
    email: 'hello@apressurfbar.com.au',
    direccion: 'Shop 1, 1837 Gold Coast Hwy, Burleigh QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0832,
    lng: 153.4488,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_025',
    nombre: 'Hard Fizz Taproom',
    email: 'hello@getfizzy.co',
    direccion: '16 Hibiscus Haven, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0865,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_026',
    nombre: 'Southport Pavilion',
    email: 'management@southportpavilion.com.au',
    direccion: '2 Barney St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9660,
    lng: 153.3987,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_027',
    nombre: 'The Malibu Racquet Club',
    email: 'hello@malibuburleigh.com',
    direccion: '1740 Gold Coast Hwy, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0843,
    lng: 153.4494,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_028',
    nombre: 'Las Palmas Bar & Restaurant',
    email: 'bookings@laspalmas.com.au',
    direccion: '1097 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1172,
    lng: 153.4660,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_029',
    nombre: 'Suga Rum Bar',
    email: 'info@sugabargc.com',
    direccion: '1142 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1180,
    lng: 153.4665,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_030',
    nombre: 'Lulu Rooftop Bar',
    email: 'info@lulurooftopbar.com.au',
    direccion: 'Level 2, 4 Orchid Avenue, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0032,
    lng: 153.4305,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_031',
    nombre: 'Sandbar Gold Coast',
    email: 'info@sandbargc.com',
    direccion: '52 Esplanade, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4302,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_032',
    nombre: "Hurricane's Grill & Bar Surfers Paradise",
    email: 'surfers@hurricanesgrillandbar.com.au',
    direccion: 'Cavill Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0030,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_033',
    nombre: 'BLVD Cafe & Bar',
    email: 'blvd@novotelsurfersparadise.com.au',
    direccion: 'Cnr Surfers Paradise Blvd & Hanlan St, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0028,
    lng: 153.4294,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_034',
    nombre: 'Steampunk Surfers Paradise',
    email: 'hello@steampunksurfersparadise.com.au',
    direccion: 'L1 3113 Surfers Paradise Blvd, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0036,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_035',
    nombre: 'Soho House Bar',
    email: 'info@sohohousebar.com.au',
    direccion: '4/2713 Gold Coast Hwy, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0340,
    lng: 153.4335,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_036',
    nombre: 'Bruce Currumbin',
    email: 'hello@brucecurrumbin.com.au',
    direccion: 'Shop 1/794 Pacific Pde, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1542,
    lng: 153.4725,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_037',
    nombre: 'Moustache Wine Bar',
    email: 'hello@moustachebar.com.au',
    direccion: '3/2217 Gold Coast Hwy, Mermaid Beach QLD 4218',
    barrio: 'Mermaid Beach',
    lat: -28.0492,
    lng: 153.4377,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_038',
    nombre: 'Kirra Beach Hotel',
    email: 'jcraig@kirrabeachhotel.com.au',
    direccion: '4 Marine Pde, Kirra QLD 4225',
    barrio: 'Kirra',
    lat: -28.1668,
    lng: 153.5330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_039',
    nombre: 'The Tropic Bar Burleigh',
    email: 'info@thetropicgc.com.au',
    direccion: '1 Goodwin Terrace, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0872,
    lng: 153.4518,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_040',
    nombre: 'Stables Bar & Kitchen',
    email: 'info@stablesbar.com.au',
    direccion: '4 Freshwater St, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0858,
    lng: 153.4500,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_041',
    nombre: 'Currumbin Creek Tavern',
    email: 'info@currumbincreektavern.com.au',
    direccion: '2172 Gold Coast Hwy, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0710,
    lng: 153.4460,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_042',
    nombre: 'The Collective Palm Beach',
    email: 'hello@thecollectivepalmbeach.com.au',
    direccion: '1071 Gold Coast Hwy, Palm Beach QLD 4221',
    barrio: 'Palm Beach',
    lat: -28.1165,
    lng: 153.4656,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_043',
    nombre: "Kurrawa Surf Club Bar",
    email: 'info@kurrawasurf.com.au',
    direccion: 'Old Burleigh Rd, Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0350,
    lng: 153.4340,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_044',
    nombre: 'Glass Dining & Lounge Bar',
    email: 'glass@sheratonmirage.com.au',
    direccion: '71 Seaworld Dr, Main Beach QLD 4217',
    barrio: 'Main Beach',
    lat: -27.9770,
    lng: 153.4100,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_045',
    nombre: 'The Pink Hotel Coolangatta',
    email: 'frontdesk@thepinkhotelcoolangatta.com',
    direccion: '171 Griffith St, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1660,
    lng: 153.5345,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_046',
    nombre: "Mano's Tedde Rave",
    email: 'info@manostedderave.com.au',
    direccion: '19-21 Tedder Ave, Main Beach QLD 4217',
    barrio: 'Main Beach',
    lat: -27.9772,
    lng: 153.4105,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_047',
    nombre: 'The Coolangatta Hotel',
    email: 'info@coolangattahotel.com.au',
    direccion: 'Cnr Warner St & Marine Pde, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1672,
    lng: 153.5342,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'bar_048',
    nombre: 'Coolangatta Sands Hotel',
    email: 'manager@coolangattasandshotel.com.au',
    direccion: 'Cnr Griffith & McLean Sts, Coolangatta QLD 4225',
    barrio: 'Coolangatta',
    lat: -28.1668,
    lng: 153.5348,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
];
