export const construccion = [
  {
    id: 'con_001',
    nombre: 'SHAPE Australia - Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Empresa de fitout y refurbishment. Mas de 30 anios de experiencia.',
  },
  {
    id: 'con_002',
    nombre: 'Coast Construct Co',
    email: 'info@coastconstructco.com.au',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0867,
    lng: 153.4510,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas de lujo, renovaciones, extensiones, decks y granny flats. Tel: 0401 774 088. QBCC #15374199.',
  },
  {
    id: 'con_003',
    nombre: 'McNab Constructions',
    email: 'recruitment@mcnab.net.au',
    direccion: '52 Township Dr, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora local grande, proyectos residenciales y comerciales.',
  },
  {
    id: 'con_004',
    nombre: 'Hutchinson Builders Gold Coast',
    email: '',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9670,
    lng: 153.4000,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Una de las constructoras mas grandes de Queensland.',
  },
  {
    id: 'con_005',
    nombre: 'FKG Group',
    email: 'hr@fkg.com.au',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0680,
    lng: 153.3820,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion, ingenieria y mantenimiento. Importante empresa de QLD.',
  },
  {
    id: 'con_006',
    nombre: 'Built Environments Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0340,
    lng: 153.4330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_007',
    nombre: 'Watpac Construction',
    email: '',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9680,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora de proyectos grandes, comerciales y civiles.',
  },
  {
    id: 'con_008',
    nombre: 'Schiavello Construction QLD',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0025,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fitout e interiores comerciales.',
  },
  {
    id: 'con_009',
    nombre: 'Lendlease Queensland',
    email: 'careers@lendlease.com',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9675,
    lng: 153.3995,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Empresa internacional, grandes proyectos de desarrollo.',
  },
  {
    id: 'con_010',
    nombre: 'Richard Crookes Constructions',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_011',
    nombre: 'Grocon Gold Coast',
    email: '',
    direccion: 'Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0335,
    lng: 153.4335,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Grandes desarrollos inmobiliarios.',
  },
  {
    id: 'con_012',
    nombre: 'Roberts Co Construction',
    email: 'enquiriesau@roberts.co',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9665,
    lng: 153.3990,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion residencial de alta densidad.',
  },
  {
    id: 'con_013',
    nombre: 'Broad Constructions',
    email: '',
    direccion: 'Gold Coast QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0342,
    lng: 153.4328,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_014',
    nombre: 'Delor Constructions',
    email: '',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0855,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora local, proyectos medianos.',
  },
  {
    id: 'con_015',
    nombre: 'GWC Construction Gold Coast',
    email: '',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0685,
    lng: 153.3815,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_016',
    nombre: 'Gold Coast Constructions',
    email: '',
    direccion: 'Helensvale QLD 4212',
    barrio: 'Helensvale',
    lat: -27.9010,
    lng: 153.3490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_017',
    nombre: 'Synergy Constructions GC',
    email: '',
    direccion: 'Varsity Lakes QLD 4227',
    barrio: 'Varsity Lakes',
    lat: -28.0960,
    lng: 153.3800,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_018',
    nombre: 'Pioneer Building Co.',
    email: '',
    direccion: 'Coomera QLD 4209',
    barrio: 'Coomera',
    lat: -27.8340,
    lng: 153.3380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion residencial en el norte de Gold Coast.',
  },
  {
    id: 'con_019',
    nombre: 'Enso Constructions',
    email: '',
    direccion: 'Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0180,
    lng: 153.4110,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_020',
    nombre: 'Halcyon Building Group',
    email: '',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9678,
    lng: 153.4002,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_021',
    nombre: 'Tomkins Constructions',
    email: 'info@tomkinsconstructions.com.au',
    direccion: '13 Precision Drive, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9752,
    lng: 153.3765,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas custom, renovaciones y construccion comercial. ABN: 93 162 525 420. QBCC #1257298. Tel: 07 5608 9849 / 0407 046 137.',
  },
  {
    id: 'con_022',
    nombre: 'Gold Coast Building Group',
    email: 'admin@goldcoastbuildinggroup.com.au',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0025,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'DN & SM Constructions. Proyectos residenciales y comerciales.',
  },
  {
    id: 'con_023',
    nombre: 'Goldberg Constructions',
    email: 'info@goldbergconstruction.com.au',
    direccion: 'Sanctuary Cove QLD 4212',
    barrio: 'Hope Island',
    lat: -27.8670,
    lng: 153.3682,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Casas de lujo. Activos en Sanctuary Cove, Hope Island y Surfers Paradise.',
  },
  {
    id: 'con_024',
    nombre: 'Gold Coast Underpinning',
    email: 'admin@goldcoastunderpinning.com.au',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9675,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fundaciones, cimentaciones y trabajos estructurales subterraneos.',
  },
  {
    id: 'con_025',
    nombre: 'Hutchinson Builders Southport',
    email: 'southport@hutchinsonbuilders.com.au',
    direccion: '92 Marine Parade, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9668,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Oficina Gold Coast de la constructora mas grande de Australia. Tel: 07 5671 7900.',
  },
  {
    id: 'con_026',
    nombre: 'JB Constructions',
    email: 'info@jbconstructionsaus.com',
    direccion: 'Gold Coast QLD',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Renovaciones, extensiones, fitouts y casas nuevas. Brisbane a Byron Bay. Tel: 0408 365 612. QBCC #15158179.',
  },
  {
    id: 'con_027',
    nombre: 'Newnham Constructions',
    email: 'info@newnhamconstructions.com.au',
    direccion: '1/51 Harper St, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9760,
    lng: 153.3760,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructora premiada en Gold Coast. Casas, remodelaciones y seguros. Tel: 07 5539 1442. QBCC #20668.',
  },
  {
    id: 'con_028',
    nombre: 'Ashley Cooper Construction',
    email: 'enquiries@ashleycooper.com',
    direccion: '174 Northgate Rd, Northgate QLD 4013',
    barrio: 'Northgate',
    lat: -27.4115,
    lng: 153.0520,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructora premiada. Opera en Brisbane y Gold Coast. Tel: 07 3142 5915.',
  },
  {
    id: 'con_029',
    nombre: 'Burleigh Constructions',
    email: 'info@burleighconstructions.com.au',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0862,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas custom de lujo. Multiple ganador HIA Awards 2020-2025. QBCC #1178916. Cubre Burleigh, Palm Beach y Broadbeach.',
  },
  {
    id: 'con_031',
    nombre: 'JT Master Builders',
    email: 'info@jtmasterbuilders.com.au',
    direccion: 'PO Box 1288, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0862,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas nuevas, renovaciones y extensiones residenciales y comerciales. Ganador HIA 2017. 20+ anos de experiencia. ABN: 69 143 458 360. QBCC #1190157. Tel: 0405 906 908.',
  },
  {
    id: 'con_030',
    nombre: 'General Building Co.',
    email: 'office@generalbuilding.co',
    direccion: 'Gold Coast QLD',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Renovaciones, reparaciones, mantenimiento residencial y comercial. ABN: 82 667 430 873. QBCC #15375295. Tel: 1300 210 423.',
  },
  {
    id: 'con_032',
    nombre: 'Hampton Homes QLD',
    email: 'info@hamptonhomes.com.au',
    direccion: '4C / 50 Currumbin Creek Rd, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1535,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructor de lujo custom, 30+ anios, multiples premios Master Builders. Casas $3M-$15M. Modelo Cost Plus. Tel: 07 5525 0722.',
  },
  {
    id: 'con_033',
    nombre: 'Mactech Constructions',
    email: 'info@mactechconstructions.com',
    direccion: 'Gold Coast QLD',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructor de lujo premiado. Ganador HIA Australian Home of the Year 2026 (Cloudbreak), HIA Townhouse, Bathroom y Kitchen of the Year. Solo Instagram + email.',
  },
  {
    id: 'con_034',
    nombre: 'Custombuilt Builders',
    email: 'roy@custombuiltbuilders.com.au',
    direccion: 'Gold Coast QLD 4223',
    barrio: 'Gold Coast Sur',
    lat: -28.1540,
    lng: 153.4500,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas nuevas, renovaciones y extensiones. Ganador Master Builders 2019. Contacto: Roy Allen. Tel: 0477 496 659.',
  },
  {
    id: 'con_035',
    nombre: 'Cameron Constructions',
    email: 'shamus@cameronconstructions.com.au',
    direccion: 'Gold Coast QLD (opera en Palm Beach, Burleigh, Mermaid, Broadbeach)',
    barrio: 'Palm Beach',
    lat: -28.1340,
    lng: 153.4660,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructor arquitectonico premiado, casas custom en el sur del GC. Contacto: Shamus Cameron. Tel: 0405 309 160. Email provisto manualmente.',
  },
  {
    id: 'con_036',
    nombre: 'Gold Coast Building Group',
    email: 'admin@goldcoastbuildinggroup.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'DN & SM Constructions Pty Ltd. Construccion comercial, project management y design & build. Tel: 0436 029 677.',
  },
  {
    id: 'con_037',
    nombre: 'Burleigh Constructions',
    email: 'info@burleighconstructions.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Custom homes y renovaciones de lujo en Gold Coast. HIA Award winner 2024/2025. QBCC #1178316. HIA Member #544956. Tel: 0424 507 135.',
  },
  {
    id: 'con_038',
    nombre: 'Newnham Constructions',
    email: '',
    direccion: 'Unit 1, 51 Harper Street, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9841,
    lng: 153.3603,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructor Gold Coast por mas de 40 anos. Residencial y comercial. QBCC #20668. Master Builders QLD. Tel: (07) 5539 1442. Sin email en el sitio, solo formulario.',
  },
  {
    id: 'con_039',
    nombre: 'Symcorp Design & Build',
    email: '',
    direccion: '5/18 Strathaird Road, Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0220,
    lng: 153.4180,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Custom homes, renovaciones y duplexes. Gold Coast, Tweed y Brisbane. QBCC #1258277. ABN: 43 990 862 073. Master Builders QLD. Tel: 1300 043 012. Sin email en sitio oficial.',
  },
  {
    id: 'con_040',
    nombre: 'Coast Construct Co',
    email: 'info@coastconstructco.com.au',
    direccion: 'Burleigh Heads, Gold Coast QLD',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas nuevas, renovaciones, extensiones, decks y granny flats. 25+ anios de experiencia. Contacto: Nathan. QBCC #15374199. ABN: 98 424 086 743. Master Builder. Tel: 0401 774 088.',
  },
  {
    id: 'con_041',
    nombre: 'Custombuilt Builders',
    email: 'roy@custombuiltbuilders.com.au',
    direccion: 'Gold Coast QLD 4223',
    barrio: 'Gold Coast',
    lat: -28.1670,
    lng: 153.5100,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas nuevas, custom builds y renovaciones. Contacto: Roy Allen. Tel: 0477 496 659. Housing & Construction Awards 2019 Regional Winner. Master Builders QLD.',
  },
  {
    id: 'con_042',
    nombre: 'HCN Co',
    email: 'Administration@hcnco.com.au',
    direccion: 'Gold Coast Highway, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Construccion civil, movimiento de tierras, project management, labour resources y plant hire. Opera en QLD y NSW. Tel: 0467 588 483.',
  },
  {
    id: 'con_043',
    nombre: 'Innovare Builders',
    email: 'info@innovarebuilders.com.au',
    direccion: 'Gold Coast QLD (oficina Brisbane: 29/97 Creek St)',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Casas de lujo, renovaciones, comercial, fit-outs, construccion remedial. Desde 1997. QBCC #15514239. ABN: 31 685 612 293. Master Builders. Tel: 0488 773 232. Cubre Gold Coast y Brisbane.',
  },
  {
    id: 'con_044',
    nombre: 'Hennessy Building Projects',
    email: 'mail@henbuild.com.au',
    direccion: 'PO Box 26, Varsity Lakes QLD 4227',
    barrio: 'Varsity Lakes',
    lat: -28.0960,
    lng: 153.3795,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Custom builds, knock-down rebuild, multi-residencial, duplexes y commercial fit-outs. 35+ anios de experiencia. Award-winning. Tel: 07 5598 5357. Lun-Vie 8am-4:30pm.',
  },
  {
    id: 'con_045',
    nombre: 'Conjax Construction',
    email: 'admin@conjax.net',
    direccion: 'Helensvale QLD 4212',
    barrio: 'Helensvale',
    lat: -27.9005,
    lng: 153.3485,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Empresa familiar Gold Coast. New builds, knock-down rebuilds, extensiones, renovaciones, trabajos de seguro y modificaciones NDIS. 25+ anios experiencia residencial y comercial. Tel: 0422 290 935.',
  },
  {
    id: 'con_046',
    nombre: 'Ashley Cooper Construction',
    email: 'enquiries@ashleycooper.com',
    direccion: '174 Northgate Rd, Northgate QLD 4013',
    barrio: 'Brisbane (atiende Gold Coast)',
    lat: -27.4100,
    lng: 153.0500,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructora commercial award-winning. Hospitality, educacion, retail y residencial. Atiende toda la Gold Coast con proyectos frecuentes en Broadbeach, Burleigh, Surfers, Southport. Tel: (07) 3142 5915. Lun-Vie 8am-5pm.',
  },
  {
    id: 'con_047',
    nombre: 'Gold Coast Building Services',
    email: 'admin@goldcoastbuild.com.au',
    direccion: 'PO Box 186, Chirn Park QLD 4215',
    barrio: 'Southport',
    lat: -27.9580,
    lng: 153.4080,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'High rise, commercial, industrial, town houses. Gold Coast especialistas. Sitio Drupal con contacto publico. Tel: no disponible en sitio.',
  },
  {
    id: 'con_048',
    nombre: 'Optima Constructions Australia',
    email: 'info@optimaconstructions.com.au',
    direccion: 'Level 13, 50 Cavill Avenue, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0023,
    lng: 153.4304,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Constructora residencial y civil en Gold Coast. Coomera, Pimpama y toda la Gold Coast. Tel: 07 5510 4839 / 0410 976 113.',
  },
];
