export const construccion = [
  {
    id: 'con_001',
    nombre: 'SHAPE Australia - Gold Coast',
    email: 'goldcoast@shape.com.au',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Empresa de fitout y refurbishment. Mas de 30 anios de experiencia.',
  },
  {
    id: 'con_002',
    nombre: 'Coast Construct Co',
    email: 'info@coastconstructco.com.au',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0050,
    lng: 153.4280,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Mas de 25 anios de experiencia en construccion residencial y comercial.',
  },
  {
    id: 'con_003',
    nombre: 'McNab Constructions',
    email: 'info@mcnab.net.au',
    direccion: '52 Township Dr, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora local grande, proyectos residenciales y comerciales.',
  },
  {
    id: 'con_004',
    nombre: 'Hutchinson Builders Gold Coast',
    email: 'goldcoast@hutchinsonbuilders.com.au',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9670,
    lng: 153.4000,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Una de las constructoras mas grandes de Queensland.',
  },
  {
    id: 'con_005',
    nombre: 'FKG Group',
    email: 'info@fkg.com.au',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0680,
    lng: 153.3820,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion, ingenieria y mantenimiento. Importante empresa de QLD.',
  },
  {
    id: 'con_006',
    nombre: 'Built Environments Gold Coast',
    email: 'qld@built.com.au',
    direccion: 'Gold Coast QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0340,
    lng: 153.4330,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_007',
    nombre: 'Watpac Construction',
    email: 'qld@watpac.com.au',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9680,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora de proyectos grandes, comerciales y civiles.',
  },
  {
    id: 'con_008',
    nombre: 'Schiavello Construction QLD',
    email: 'qld@schiavello.com',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0025,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fitout e interiores comerciales.',
  },
  {
    id: 'con_009',
    nombre: 'Lendlease Queensland',
    email: 'qld@lendlease.com',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9675,
    lng: 153.3995,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Empresa internacional, grandes proyectos de desarrollo.',
  },
  {
    id: 'con_010',
    nombre: 'Richard Crookes Constructions',
    email: 'qld@rccpl.com.au',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_011',
    nombre: 'Grocon Gold Coast',
    email: 'info@grocon.com.au',
    direccion: 'Broadbeach QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0335,
    lng: 153.4335,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Grandes desarrollos inmobiliarios.',
  },
  {
    id: 'con_012',
    nombre: 'Roberts Co Construction',
    email: 'info@robertsco.com.au',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9665,
    lng: 153.3990,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion residencial de alta densidad.',
  },
  {
    id: 'con_013',
    nombre: 'Broad Constructions',
    email: 'info@broad.com.au',
    direccion: 'Gold Coast QLD 4218',
    barrio: 'Broadbeach',
    lat: -28.0342,
    lng: 153.4328,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_014',
    nombre: 'Delor Constructions',
    email: 'info@delorconstructions.com.au',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0855,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora local, proyectos medianos.',
  },
  {
    id: 'con_015',
    nombre: 'GWC Construction Gold Coast',
    email: 'projects@gwcconstruction.com.au',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0685,
    lng: 153.3815,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_016',
    nombre: 'Gold Coast Constructions',
    email: 'info@gconstructions.com.au',
    direccion: 'Helensvale QLD 4212',
    barrio: 'Helensvale',
    lat: -27.9010,
    lng: 153.3490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_017',
    nombre: 'Synergy Constructions GC',
    email: 'hello@synergygc.com.au',
    direccion: 'Varsity Lakes QLD 4227',
    barrio: 'Varsity Lakes',
    lat: -28.0960,
    lng: 153.3800,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_018',
    nombre: 'Pioneer Building Co.',
    email: 'info@pioneerbuildingco.com.au',
    direccion: 'Coomera QLD 4209',
    barrio: 'Coomera',
    lat: -27.8340,
    lng: 153.3380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Construccion residencial en el norte de Gold Coast.',
  },
  {
    id: 'con_019',
    nombre: 'Enso Constructions',
    email: 'info@ensoconstructions.com.au',
    direccion: 'Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0180,
    lng: 153.4110,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_020',
    nombre: 'Halcyon Building Group',
    email: 'build@halcyongroup.com.au',
    direccion: 'Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9678,
    lng: 153.4002,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: '',
  },
  {
    id: 'con_021',
    nombre: 'Tomkins Constructions',
    email: 'info@tomkinsconstructions.com.au',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0858,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Constructora de casas custom y renovaciones en Gold Coast.',
  },
  {
    id: 'con_022',
    nombre: 'Gold Coast Building Group',
    email: 'admin@goldcoastbuildinggroup.com.au',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0025,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'DN & SM Constructions. Proyectos residenciales y comerciales.',
  },
  {
    id: 'con_023',
    nombre: 'Goldberg Constructions',
    email: 'info@goldbergconstruction.com.au',
    direccion: 'Sanctuary Cove QLD 4212',
    barrio: 'Hope Island',
    lat: -27.8670,
    lng: 153.3682,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Casas de lujo. Activos en Sanctuary Cove, Hope Island y Surfers Paradise.',
  },
  {
    id: 'con_024',
    nombre: 'Gold Coast Underpinning',
    email: 'admin@goldcoastunderpinning.com.au',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9675,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fundaciones, cimentaciones y trabajos estructurales subterraneos.',
  },
  {
    id: 'con_025',
    nombre: 'Hutchinson Builders Southport',
    email: 'southport@hutchinsonbuilders.com.au',
    direccion: '92 Marine Parade, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9668,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Oficina Gold Coast de la constructora mas grande de Australia. Tel: 07 5671 7900.',
  },
];
