export const fabricas = [
  {
    id: 'fab_001',
    nombre: 'Ausfab Stainless Pty Ltd',
    email: 'sales@ausfabstainless.com.au',
    direccion: 'Helensvale QLD 4212',
    barrio: 'Helensvale',
    lat: -27.9005,
    lng: 153.3485,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion en acero inoxidable. Fundada por Marc Norgrove y Wayne Carr.',
  },
  {
    id: 'fab_002',
    nombre: 'SCL Welding',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0857,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'MIG, TIG, arco. Acero, aluminio, inoxidable. Mas de 20 anios.',
  },
  {
    id: 'fab_003',
    nombre: 'QLD Metal Recyclers',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8340,
    lng: 153.3500,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Reciclado de metales. Fundada en 2003.',
  },
  {
    id: 'fab_004',
    nombre: 'Hydraulink Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Mangueras y fittings hidraulicos. Fabricacion y mantenimiento.',
  },
  {
    id: 'fab_005',
    nombre: 'Hydraulink Yatala',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8335,
    lng: 153.3498,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Sucursal de Hydraulink en Yatala.',
  },
  {
    id: 'fab_006',
    nombre: 'Plastics Online Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0850,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion de plastico personalizada: acrilico, policarbonato, PVC.',
  },
  {
    id: 'fab_007',
    nombre: 'Evolve Skateboards',
    email: 'ask@rideevolve.com.au',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0862,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion de skates electricos. Empresa tecnologica local.',
  },
  {
    id: 'fab_008',
    nombre: 'Alive Technologies',
    email: 'info@alivetec.com',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9672,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Manufactura de dispositivos electronicos.',
  },
  {
    id: 'fab_009',
    nombre: 'Coast Metal Fabrication',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8338,
    lng: 153.3505,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion metalica general. Chapa, perfiles y estructuras.',
  },
  {
    id: 'fab_010',
    nombre: 'GC Powder Coating',
    email: '',
    direccion: 'Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1540,
    lng: 153.4715,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Recubrimiento en polvo para metales industriales.',
  },
  {
    id: 'fab_011',
    nombre: 'Euro Pumps Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0854,
    lng: 153.4493,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Diseno y fabricacion de equipos de limpieza industrial.',
  },
  {
    id: 'fab_012',
    nombre: 'GC Sheet Metal Works',
    email: '',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0682,
    lng: 153.3818,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Trabajos en chapa: ductos, canaletas, estructuras.',
  },
  {
    id: 'fab_013',
    nombre: 'Neumann Engineering GC',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0028,
    lng: 153.4297,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Ingenieria estructural y mecanica.',
  },
  {
    id: 'fab_014',
    nombre: 'Coomera Industrial Supply',
    email: '',
    direccion: 'Coomera QLD 4209',
    barrio: 'Coomera',
    lat: -27.8342,
    lng: 153.3375,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Suministros industriales y logistica.',
  },
  {
    id: 'fab_015',
    nombre: 'Pacific Industrial Products',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8330,
    lng: 153.3495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Productos industriales para construccion y mantenimiento.',
  },
  {
    id: 'fab_016',
    nombre: 'GC Foods Manufacturing',
    email: '',
    direccion: 'Racecourse Dr, Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0182,
    lng: 153.4105,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Manufactura de alimentos: salsas, tartas, sopas. Certificado HACCP. Cocina HACCP.',
  },
  {
    id: 'fab_017',
    nombre: 'Neumann Industrial Coatings',
    email: 'info@neumanncontractors.com.au',
    direccion: '13 Nuban St, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1535,
    lng: 153.4718,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Division de Neumann Contractors. Blasting y pintura industrial. Tel: 07 5589 9303.',
  },
];
