export const fabricas = [
  {
    id: 'fab_001',
    nombre: 'Ausfab Stainless Pty Ltd',
    email: 'sales@ausfabstainless.com.au',
    direccion: 'Helensvale QLD 4212',
    barrio: 'Helensvale',
    lat: -27.9005,
    lng: 153.3485,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion en acero inoxidable. Fundada por Marc Norgrove y Wayne Carr.',
  },
  {
    id: 'fab_002',
    nombre: 'SCL Welding',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0857,
    lng: 153.4495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'MIG, TIG, arco. Acero, aluminio, inoxidable. Mas de 20 anios.',
  },
  {
    id: 'fab_003',
    nombre: 'QLD Metal Recyclers',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8340,
    lng: 153.3500,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Reciclado de metales. Fundada en 2003.',
  },
  {
    id: 'fab_004',
    nombre: 'Hydraulink Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0022,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Mangueras y fittings hidraulicos. Fabricacion y mantenimiento.',
  },
  {
    id: 'fab_005',
    nombre: 'Hydraulink Yatala',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8335,
    lng: 153.3498,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Sucursal de Hydraulink en Yatala.',
  },
  {
    id: 'fab_006',
    nombre: 'Plastics Online Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0850,
    lng: 153.4490,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion de plastico personalizada: acrilico, policarbonato, PVC.',
  },
  {
    id: 'fab_007',
    nombre: 'Evolve Skateboards',
    email: 'ask@rideevolve.com.au',
    direccion: 'Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0862,
    lng: 153.4502,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion de skates electricos. Empresa tecnologica local.',
  },
  {
    id: 'fab_008',
    nombre: 'Alive Technologies',
    email: 'info@alivetec.com',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9672,
    lng: 153.3998,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Manufactura de dispositivos electronicos.',
  },
  {
    id: 'fab_009',
    nombre: 'Coast Metal Fabrication',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8338,
    lng: 153.3505,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion metalica general. Chapa, perfiles y estructuras.',
  },
  {
    id: 'fab_010',
    nombre: 'GC Powder Coating',
    email: '',
    direccion: 'Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1540,
    lng: 153.4715,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Recubrimiento en polvo para metales industriales.',
  },
  {
    id: 'fab_011',
    nombre: 'Euro Pumps Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0854,
    lng: 153.4493,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Diseno y fabricacion de equipos de limpieza industrial.',
  },
  {
    id: 'fab_012',
    nombre: 'GC Sheet Metal Works',
    email: '',
    direccion: 'Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0682,
    lng: 153.3818,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Trabajos en chapa: ductos, canaletas, estructuras.',
  },
  {
    id: 'fab_013',
    nombre: 'Neumann Engineering GC',
    email: '',
    direccion: 'Gold Coast QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0028,
    lng: 153.4297,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Ingenieria estructural y mecanica.',
  },
  {
    id: 'fab_014',
    nombre: 'Coomera Industrial Supply',
    email: '',
    direccion: 'Coomera QLD 4209',
    barrio: 'Coomera',
    lat: -27.8342,
    lng: 153.3375,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Suministros industriales y logistica.',
  },
  {
    id: 'fab_015',
    nombre: 'Pacific Industrial Products',
    email: '',
    direccion: 'Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8330,
    lng: 153.3495,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Productos industriales para construccion y mantenimiento.',
  },
  {
    id: 'fab_016',
    nombre: 'GC Foods Manufacturing',
    email: 'info@gcfoods.com.au',
    direccion: 'Racecourse Dr, Bundall QLD 4217',
    barrio: 'Bundall',
    lat: -28.0182,
    lng: 153.4105,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Manufactura de alimentos: salsas, tartas, sopas. Cocina HACCP certificada. Private label y retail. Tel: +61 405 449 839.',
  },
  {
    id: 'fab_017',
    nombre: 'Neumann Industrial Coatings',
    email: 'info@neumanncontractors.com.au',
    direccion: '13 Nuban St, Currumbin QLD 4223',
    barrio: 'Currumbin',
    lat: -28.1535,
    lng: 153.4718,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Division de Neumann Contractors. Blasting y pintura industrial. Tel: 07 5589 9303.',
  },
  {
    id: 'fab_018',
    nombre: 'Dynaton Sales & Hire',
    email: 'sales@dynaton.com.au',
    direccion: '213 Sandy Creek Road, Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8333,
    lng: 153.3488,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Venta y alquiler de encofrado, andamios, EPP y herramientas. 100% australiano. Tel: 07 3287 4633.',
  },
  {
    id: 'fab_019',
    nombre: 'Marine Tech Industries',
    email: 'sales@marinetechindustries.com',
    direccion: '23 Commerce Circuit, Yatala QLD 4207',
    barrio: 'Yatala',
    lat: -27.8338,
    lng: 153.3502,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de productos nauticos. Oficina tambien en Melbourne (VIC). Tel: 1300 300 089.',
  },
  {
    id: 'fab_020',
    nombre: 'Gillcraft Welding',
    email: 'info@gillcraftwelding.com.au',
    direccion: '19 Demand Avenue, Arundel QLD 4214',
    barrio: 'Arundel',
    lat: -27.9560,
    lng: 153.3620,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion en acero desde 1983. MIG, TIG, soldadura estructural. Gold Coast. Tel: 07 5594 0125.',
  },
  {
    id: 'fab_021',
    nombre: 'Davis Welding and Fabrication',
    email: 'kynan@davisweldandfab.com.au',
    direccion: '26 Horizon Drive, Beenleigh QLD 4207',
    barrio: 'Beenleigh',
    lat: -27.7158,
    lng: 153.1836,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura y fabricacion comercial. Acero inoxidable, galvanizado y aluminio. Atiende Brisbane y Gold Coast. QBCC #15466603. Tel: 0416 337 597.',
  },
  {
    id: 'fab_023',
    nombre: "Brumb's Welding & Fabrication",
    email: 'brumbsmarine@bigpond.com',
    direccion: 'Shed 1/657 Pine Ridge Rd, Biggera Waters QLD 4216',
    barrio: 'Biggera Waters',
    lat: -27.9420,
    lng: 153.3580,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'TIG, MIG, soldadura marina y fabricacion de aluminio. Ponton y muelle. Tel: 0416 209 590. Lun-Sab 7am-3pm.',
  },
  {
    id: 'fab_024',
    nombre: 'Arcs & Sparks Engineering',
    email: 'info@arcsandsparks.com.au',
    direccion: 'Unit 2, 1 Demand Avenue, Arundel QLD 4214',
    barrio: 'Arundel',
    lat: -27.9562,
    lng: 153.3618,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Mas de 30 anios. MIG, TIG, aluminio, acero. Soldadura movil, sandblasting y camiones grua. Plasma cutting hasta 80mm. Tel: 0429 931 050. Lun-Vie 6am-4pm.',
  },
  {
    id: 'fab_025',
    nombre: 'SF Fabrications',
    email: 'office@sffab.com.au',
    direccion: '26 Mercantile Court, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9750,
    lng: 153.3765,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Acero inoxidable, aluminio, cobre, laton y acero. Plasma cutting, powder coating, mesadas comerciales. ABN: 87 133 090 856. Tel: 07 5574 4951. Lun-Jue 6am-3pm, Vie 6am-1pm.',
  },
  {
    id: 'fab_022',
    nombre: 'Ashmore Welding',
    email: '',
    direccion: '10 Indy Ct, Carrara QLD 4211',
    barrio: 'Carrara',
    lat: -28.0290,
    lng: 153.3680,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Mas de 20 anios en Gold Coast. MIG, TIG, arco. Acero estructural, drafting, rigging e instalacion. Tel: 07 5596 3021.',
  },
  {
    id: 'fab_027',
    nombre: 'EXP Plastics',
    email: 'info@expplastics.com.au',
    direccion: '13 Distribution Ave, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9752,
    lng: 153.3763,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de plasticos desde 2003. Familia Bar. CNC, laser cutting, perspex, policarbonato, componentes marinos. Solar-powered. Tel: 07 5620 1038. Lun-Jue 7:30am-4pm, Vie hasta 3:30pm.',
  },
  {
    id: 'fab_028',
    nombre: 'Holland Plastics',
    email: 'sales@hollandplastics.com.au',
    direccion: '13 Distribution Avenue, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9752,
    lng: 153.3763,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de plasticos e ingenieria. CNC, laser, vacuum forming, thermoforming, acrilico, policarbonato y mas. Tel: 07 5564 6744. Lun-Jue 7:30am-4pm, Vie hasta 3:30pm.',
  },
  {
    id: 'fab_029',
    nombre: 'Rankin Steel & Rigging',
    email: 'tony@rankinsteel.com.au',
    direccion: '21 Sinclair Street, Arundel QLD 4214',
    barrio: 'Arundel',
    lat: -27.9565,
    lng: 153.3615,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de acero, grua, erección estructural, soldadura movil, galvanizado. ABN: 48 109 763 902. BSA Licence: 713 231. Tel: 07 5537 9387. Contacto: Tony Rankin 0418 736 413. Tambien: steve@rankinsteel.com.au (Steve Waldron).',
  },
  {
    id: 'fab_030',
    nombre: 'SFAB Engineering',
    email: 'john@sfabengineering.com',
    direccion: '23 Keller Crescent, Carrara QLD 4211',
    barrio: 'Carrara',
    lat: -28.0290,
    lng: 153.3545,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de acero custom, ventanas y puertas de alta seguridad, ventanas con marco de acero. Empresa familiar, est. 2015, 20+ anios experiencia. Tel: 0400 579 990.',
  },
  {
    id: 'fab_031',
    nombre: 'Cel-Bar Powder Coatings',
    email: 'cel-bar@hotmail.com',
    direccion: '21 Reichert Drive, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9634,
    lng: 153.3559,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Powder coating industrial y residencial. On call 24/7. Tel: 1300 966 388 / 0416 612 386. Tambien: quote@cel-bar.com.au. Lun-Vie 7am-5pm, Sab-Dom con cita.',
  },
  {
    id: 'fab_032',
    nombre: 'Gold Coast Powder Coating',
    email: 'gcpowdercoating@optusnet.com.au',
    direccion: '8 Kimberley Road, Burleigh Gardens QLD 4220',
    barrio: 'Burleigh Gardens',
    lat: -28.0900,
    lng: 153.4450,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Powder coating, sand blasting y servicios cromaticos. Domestic, comercial e industrial. ABN: 98 095 549 938. Tel: 07 5593 4366. Lun-Vie 7am-4pm.',
  },
  {
    id: 'fab_033',
    nombre: 'Vision Metal Works',
    email: 'visionmw@bigpond.net.au',
    direccion: 'Unit 4/20 Hilldon Court, Nerang QLD 4211',
    barrio: 'Nerang',
    lat: -27.9991,
    lng: 153.3438,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion metalica desde 1998. Inoxidable, acero, aluminio, galvanizado. Kitchens comerciales, canopies automotrices, cuerpos corporativos. QBCC: 1188201. ABN: 47 105 191 857. Tel: 07 5527 4130 / 0412 244 774. Lun-Jue 7am-4pm, Vie 7am-2pm.',
  },
  {
    id: 'fab_034',
    nombre: 'Southern Stainless',
    email: 'sales@southernstainless.com.au',
    direccion: '39 Notar Drive, Ormeau QLD 4208',
    barrio: 'Ormeau',
    lat: -27.7950,
    lng: 153.2990,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Artesanos en acero inoxidable. 30+ anios de experiencia. Marina, residencial, comercial. Waterjet, CNC, laser, electropolishing. Semana de 4 dias (lunes a jueves 7am-4pm). Tel: (07) 5549 0560.',
  },
  {
    id: 'fab_035',
    nombre: 'FIVE92 Welding & Fabrication',
    email: 'five92fabrications@hotmail.com',
    direccion: 'Gold Coast / Brisbane QLD',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura y fabricacion custom. Mobile welding Gold Coast. Estructural, inoxidable, marina. Labour hire disponible. Tel: 0430 746 030.',
  },
  {
    id: 'fab_036',
    nombre: 'Bowden Welding Service',
    email: 'admin@bowdenweldingservice.com.au',
    direccion: '39 Taree Street, Burleigh Heads QLD 4220',
    barrio: 'Burleigh Heads',
    lat: -28.0845,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura estructural y fabricacion. Gold Coast, Brisbane y Northern Rivers. ABN: 98 153 261 968. Tel: 07 5593 4831. Lun-Vie.',
  },
  {
    id: 'fab_026',
    nombre: "Dingo's Welding",
    email: 'admin@dingoswelding.com',
    direccion: '16 Kambalda Court, Worongary QLD 4213',
    barrio: 'Worongary',
    lat: -28.0600,
    lng: 153.3490,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura movil Gold Coast-Brisbane. MIG, TIG, Stick, Flux Core. Acero, inoxidable, aluminio. ABN: 60378043165. Tel: 0415 245 576.',
  },
  {
    id: 'fab_041',
    nombre: 'Gillcraft Welding',
    email: 'info@gillcraftwelding.com.au',
    direccion: '19 Demand Avenue, Arundel QLD 4214',
    barrio: 'Arundel',
    lat: -27.9590,
    lng: 153.3750,
    status: 'Pendiente',
    emailVerified: true,
    hidden: true,
    notas: 'Acero estructural, metalwork residencial y comercial, modificaciones de contenedores maritimos. Desde 1983. Cubre Gold Coast, Nerang, Arundel, Biggera Waters, Hope Island, Brisbane. ABN: 26 249 104 782. Tel: 07 5594 0125.',
  },
  {
    id: 'fab_042',
    nombre: 'Davis Welding & Fabrication',
    email: 'kynan@davisweldandfab.com.au',
    direccion: '18 Pease Court, Bethania QLD 4205',
    barrio: 'Bethania',
    lat: -27.7080,
    lng: 153.1750,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion metalica comercial. Soldadura estructural, alimenticia, galvanizada y boilermaking. Cubre Brisbane y Gold Coast. QBCC #15466603. Tel: 0416 337 597. Oficina 5am-2pm, operaciones 7 dias. Solo comercial.',
  },
  {
    id: 'fab_039',
    nombre: 'SF Fabrications',
    email: 'office@sffab.com.au',
    direccion: '26 Mercantile Court, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9510,
    lng: 153.3550,
    status: 'Pendiente',
    emailVerified: true,
    hidden: true,
    notas: 'Acero inoxidable, aluminio, cobre, bronce, acero ligero/pesado, plasma cutting y powder coating. Fabricacion custom. ABN: 87 133 090 856. Tel: 07 5574 4951. Lun-Jue 6am-3pm, Vie 6am-1pm.',
  },
  {
    id: 'fab_040',
    nombre: 'Nerang Plastics',
    email: 'nerangplastics@gmail.com',
    direccion: '1 Kamholtz Court, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9515,
    lng: 153.3548,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de plastico, CNC y laser, ventanas y escotillas para embarcaciones, impresion 3D resin, paneles composite de aluminio. Cubre Gold Coast, Brisbane, Sunshine Coast y hasta Cairns. Tel: 0490 916 431 / 0433 229 801. Lun-Vie 8:30am-4pm.',
  },
  {
    id: 'fab_037',
    nombre: 'SFAB Engineering',
    email: 'john@sfabengineering.com',
    direccion: 'Unit 2/23 Keller Crescent, Carrara QLD 4211',
    barrio: 'Carrara',
    lat: -28.0550,
    lng: 153.3720,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de acero y ventanas/puertas de alta seguridad. Aplicaciones comerciales, residenciales y correccionales. Tel: 0400 579 990.',
  },
  {
    id: 'fab_038',
    nombre: "Brumb's Welding & Fabrication",
    email: 'brumbsmarine@bigpond.com',
    direccion: 'Shed 1/657 Pine Ridge Rd, Biggera Waters QLD 4216',
    barrio: 'Biggera Waters',
    lat: -27.9320,
    lng: 153.3940,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'TIG/MIG, soldadura marina, aluminio, reparacion de pontones y muelles. ABN: 34 103 389 117. Tel: 0416 209 590. Lun-Sab 7am-3pm.',
  },
  {
    id: 'fab_043',
    nombre: 'PCS Engineering',
    email: 'paul.kowski@gmail.com',
    direccion: 'PO Box 1580, Mudgeeraba QLD 4213',
    barrio: 'Mudgeeraba',
    lat: -28.0820,
    lng: 153.3620,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura movil y fabricacion custom Gold Coast. Line boring, reparacion de maquinaria y excavadoras, soldadura de equipos y plantas. Propietario: Paul Kowski. Tel: 0439 660 206. Lun-Vie 6am-5pm, Sab-Dom con cita.',
  },
  {
    id: 'fab_044',
    nombre: 'ASAP Welding',
    email: 'gibby@asapwelding.com.au',
    direccion: 'Unit 2, 11 Brendan Drive, Nerang QLD 4211',
    barrio: 'Nerang',
    lat: -27.9988,
    lng: 153.3421,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: '35+ anios experiencia. MIG, Arc, TIG aluminio, inoxidable, oxy y plasma cutting. Ligero a pesado. Camiones, trailers, barcos, maquinaria agricola, reparaciones comerciales. ABN: 54 687 351 088. Tel: 0402 212 684. Lun-Jue 6am-5pm, Vie 6am-4pm.',
  },
  {
    id: 'fab_045',
    nombre: "Mick's Marine Maintenance",
    email: 'info@micksmarinemaintenance.com.au',
    direccion: 'Runaway Bay QLD 4216',
    barrio: 'Runaway Bay',
    lat: -27.9150,
    lng: 153.3890,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Soldadura y fabricacion de aluminio marino. Pontones, gangways, barcazas custom, reparaciones en sitio y en taller. Cubre Gold Coast, Brisbane, Sunshine Coast y Northern NSW. ABN: 54 392 368 210. Tel: 0431 778 468.',
  },
  {
    id: 'fab_046',
    nombre: 'Vision Metal Works',
    email: 'visionmw@bigpond.net.au',
    direccion: '4/20 Hilldon Court, Nerang QLD 4211',
    barrio: 'Nerang',
    lat: -28.0003,
    lng: 153.3437,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Fabricacion de chapa metalica desde 1998. Acero inoxidable, aluminio, galvanizado, zincanneal, canopies automotrices, cocinas comerciales, trolleys, armarios y reparaciones. Tel: 07 5527 4130 / 0412 244 774. Lun-Jue 7am-4pm, Vie 7am-2pm. QBCC/BSA: 1188201.',
  },
  {
    id: 'fab_047',
    nombre: 'Arcs & Sparks Engineering',
    email: 'info@arcsandsparks.com.au',
    direccion: 'Unit 2, 1 Demand Avenue, Arundel QLD 4214',
    barrio: 'Arundel',
    lat: -27.9490,
    lng: 153.3520,
    status: 'Pendiente',
    emailVerified: true,
    hidden: true,
    notas: 'DUPLICADO de fab_024.',
  },
  {
    id: 'fab_049',
    nombre: 'DL Steel Fabrications',
    email: '',
    direccion: '17 Quarry Road, Stapylton QLD 4207',
    barrio: 'Stapylton',
    lat: -27.7490,
    lng: 153.2380,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Fabricacion estructural de acero para residencial y comercial. Stapylton (Yatala North). Desde casas hasta grandes apartamentos comerciales, gates industriales. ABN: 627124092. Tel: 04 7873 8668. Sin email en sitio.',
  },
  {
    id: 'fab_050',
    nombre: 'Starline Powder Coating',
    email: '',
    direccion: '16 Expansion Street, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9771,
    lng: 153.3562,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Powder coating industrial y decorativo. Dulux/Interpon/AkzoNobel/Jotun. ABN: 79 621 694 193. Tel: (07) 5564 7177 / 0432 220 733. Sin email en sitio, solo formulario.',
  },
  {
    id: 'fab_051',
    nombre: 'Bundall Powder Coating',
    email: 'admin@bundallpc.com.au',
    direccion: '22 Expansion Street, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9760,
    lng: 153.3561,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Powder coating, sandblasting, laser cutting y pre-treatment. Servicios decorativos e industriales. Tel: (07) 5539 6177.',
  },
  {
    id: 'fab_052',
    nombre: 'Procoat Industries',
    email: '',
    direccion: '14 Enterprise Street, Molendinar QLD 4214',
    barrio: 'Molendinar',
    lat: -27.9770,
    lng: 153.3595,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Powder coating y recubrimientos industriales. Tel: 07 5597 2227. Sin email visible en sitio.',
  },
  {
    id: 'fab_053',
    nombre: 'Gold Coast Food Productions',
    email: 'jack@goldcoastfoodproductions.com',
    direccion: '30 Christine Ave, Miami QLD 4220',
    barrio: 'Miami',
    lat: -28.0760,
    lng: 153.4450,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Produccion de alimentos envasados al vacio para restaurantes y negocios de comida. Salsas, proteinas sous-vide, productos bistro/pub y cocina asiatica/mediterranea. Tel: 0421 100 326. Lun-Jue 7am-7pm, Vie-Sab 7am-4pm.',
  },
  {
    id: 'fab_048',
    nombre: 'A & K Innovations Engineering',
    email: 'jeff@akinnovations.com.au',
    direccion: 'Unit 27, 3-15 Jackman Street, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9407,
    lng: 153.3186,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Desde 1985. Torno y fresa, fabricacion de acero y aluminio, TIG, MIG, soldadura pesada, CAD/Inventor, instalacion en sitio, ingenieria industrial y construccion. Contacto: Jeff 0438 279 202.',
  },
];
