export const reclutadoras = [
  {
    id: 'rec_001',
    nombre: 'Hays Recruitment Gold Coast',
    email: 'goldcoast@hays.com.au',
    direccion: 'Level 11, 12-14 Marine Parade, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9708,
    lng: 153.4167,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Agencia internacional. Especialistas en contabilidad, tecnologia, construccion, salud. Tel: 07 5667 5200.',
  },
  {
    id: 'rec_002',
    nombre: 'AWX Gold Coast',
    email: 'goldcoast@awx.com.au',
    direccion: 'Unit 15, 18 Campus Crescent, Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0650,
    lng: 153.3820,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire y reclutamiento. Civil, construccion, alimentos, logistica. Tel: 07 5654 5290.',
  },
  {
    id: 'rec_003',
    nombre: 'JV Recruitment Gold Coast',
    email: 'info@jvrecruitment.com.au',
    direccion: 'Level 13, 50 Cavill Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0023,
    lng: 153.4304,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Especialistas en construccion, civil e infraestructura, manufactura y energia. Tel: 1300 CALL JV.',
  },
  {
    id: 'rec_004',
    nombre: 'WorkPac Gold Coast',
    email: 'contactus@workpac.com',
    direccion: 'Gold Coast QLD',
    barrio: 'Southport',
    lat: -27.9700,
    lng: 153.4000,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Mineria, construccion, salud, logistica. Labour hire y reclutamiento. Tel: 1300 967 572.',
  },
  {
    id: 'rec_005',
    nombre: 'The Recruitment People',
    email: 'info@therecruitmentpeople.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Reclutamiento de ventas, management y soporte. Basada en Gold Coast. Tel: 0452 019 049.',
  },
  {
    id: 'rec_006',
    nombre: 'PK Workforce',
    email: 'info@pkworkforce.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Southport',
    lat: -27.9690,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Construccion, ingenieria, mineria, logistica y hospitality. Licencia QLD: LHL-08061-K3C5B.',
  },
  {
    id: 'rec_007',
    nombre: 'Fast Labour Hire Gold Coast',
    email: 'info@fastlabourhire.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire en construccion, manufactura y eventos. Tel: 1300 700 003.',
  },
  {
    id: 'rec_008',
    nombre: 'Whitefox Recruitment',
    email: '',
    direccion: 'Gold Coast QLD (solo con turno)',
    barrio: 'Southport',
    lat: -27.9705,
    lng: 153.4010,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Permanente y contrato. SE Queensland. Solo por cita. Tel: 07 5619 7075.',
  },
  {
    id: 'rec_009',
    nombre: 'Randstad Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9715,
    lng: 153.3980,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Agencia global. Construccion, defensa, educacion, ingenieria, salud.',
  },
  {
    id: 'rec_010',
    nombre: 'Drake International Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD',
    barrio: 'Surfers Paradise',
    lat: -28.0018,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Agencia internacional. Mas de 70 anios de experiencia. Tel: 07 5555 0622.',
  },
  {
    id: 'rec_011',
    nombre: 'HJ Recruitment',
    email: '',
    direccion: 'Gold Coast QLD',
    barrio: 'Robina',
    lat: -28.0655,
    lng: 153.3815,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Blue collar. HVAC, electrica, plomeria, incendio, construccion. Tel: 0485 981 960.',
  },
  {
    id: 'rec_012',
    nombre: 'Omni Recruit',
    email: '',
    direccion: 'Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0025,
    lng: 153.4300,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Reclutadora local de Gold Coast. Tel: 07 5570 1323.',
  },
];
