export const reclutadoras = [
  {
    id: 'rec_001',
    nombre: 'Hays Recruitment Gold Coast',
    email: 'goldcoast@hays.com.au',
    direccion: 'Level 11, 12-14 Marine Parade, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9708,
    lng: 153.4167,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Agencia internacional. Especialistas en contabilidad, tecnologia, construccion, salud. Tel: 07 5667 5200.',
  },
  {
    id: 'rec_002',
    nombre: 'AWX Gold Coast',
    email: 'goldcoast@awx.com.au',
    direccion: 'Unit 15, 18 Campus Crescent, Robina QLD 4226',
    barrio: 'Robina',
    lat: -28.0650,
    lng: 153.3820,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire y reclutamiento. Civil, construccion, alimentos, logistica. Tel: 07 5654 5290.',
  },
  {
    id: 'rec_003',
    nombre: 'JV Recruitment Gold Coast',
    email: 'info@jvrecruitment.com.au',
    direccion: 'Level 13, 50 Cavill Ave, Surfers Paradise QLD 4217',
    barrio: 'Surfers Paradise',
    lat: -28.0023,
    lng: 153.4304,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Especialistas en construccion, civil e infraestructura, manufactura y energia. Tel: 1300 CALL JV.',
  },
  {
    id: 'rec_004',
    nombre: 'WorkPac Gold Coast',
    email: 'contactus@workpac.com',
    direccion: 'Gold Coast QLD',
    barrio: 'Southport',
    lat: -27.9700,
    lng: 153.4000,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Mineria, construccion, salud, logistica. Labour hire y reclutamiento. Tel: 1300 967 572.',
  },
  {
    id: 'rec_005',
    nombre: 'The Recruitment People',
    email: 'info@therecruitmentpeople.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Burleigh Heads',
    lat: -28.0860,
    lng: 153.4480,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Reclutamiento de ventas, management y soporte. Basada en Gold Coast. Tel: 0452 019 049.',
  },
  {
    id: 'rec_006',
    nombre: 'PK Workforce',
    email: 'info@pkworkforce.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Southport',
    lat: -27.9690,
    lng: 153.4005,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Construccion, ingenieria, mineria, logistica y hospitality. Licencia QLD: LHL-08061-K3C5B.',
  },
  {
    id: 'rec_007',
    nombre: 'Fast Labour Hire Gold Coast',
    email: 'info@fastlabourhire.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Surfers Paradise',
    lat: -28.0020,
    lng: 153.4298,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire en construccion, manufactura y eventos. Tel: 1300 700 003.',
  },
  {
    id: 'rec_008',
    nombre: 'Whitefox Recruitment',
    email: '',
    direccion: 'Level 3, 35-59 Scarborough St, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9705,
    lng: 153.4010,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Permanente y contrato. SE Queensland. Solo por cita. Tel: 07 5619 7075.',
  },
  {
    id: 'rec_009',
    nombre: 'Randstad Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD 4215',
    barrio: 'Southport',
    lat: -27.9715,
    lng: 153.3980,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Agencia global. Construccion, defensa, educacion, ingenieria, salud.',
  },
  {
    id: 'rec_010',
    nombre: 'Drake International Gold Coast',
    email: '',
    direccion: 'Gold Coast QLD',
    barrio: 'Surfers Paradise',
    lat: -28.0018,
    lng: 153.4295,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Agencia internacional. Mas de 70 anios de experiencia. Tel: 07 5555 0622.',
  },
  {
    id: 'rec_011',
    nombre: 'HJ Recruitment',
    email: '',
    direccion: 'Gold Coast QLD',
    barrio: 'Robina',
    lat: -28.0655,
    lng: 153.3815,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Blue collar. HVAC, electrica, plomeria, incendio, construccion. Tel: 0485 981 960.',
  },
  {
    id: 'rec_012',
    nombre: 'Omni Recruit',
    email: 'goldcoast@omnirecruit.com.au',
    direccion: 'Suite 4, 21 Lake Street, Varsity Lakes QLD 4227',
    barrio: 'Varsity Lakes',
    lat: -28.0960,
    lng: 153.3795,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Reclutadora local de Gold Coast. Tel: 07 5570 1323.',
  },
  {
    id: 'rec_013',
    nombre: 'CT Labour Hire',
    email: 'admin@ctlh.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Springwood',
    lat: -27.6020,
    lng: 153.1035,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Mas de 15 anios de experiencia. Construccion, manufactura, logistica, almacen. Tel: 1300 240 035. QBCC #15052987.',
  },
  {
    id: 'rec_015',
    nombre: 'ALH Recruitment Gold Coast',
    email: 'timc@alhltd.com.au',
    direccion: 'Gold Coast QLD',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire. Construccion, civil, manufactura, logistica y transporte. Contacto directo GC: Tim C. Tel: +61 434 473 472.',
  },
  {
    id: 'rec_016',
    nombre: 'TradeConnex',
    email: 'info@tradeconnex.com.au',
    direccion: 'Gold Coast QLD (opera en toda QLD y Australia)',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Labour hire y reclutamiento permanente. Construccion, civil, energia renovable y solar. Tel: 1300 995 234. Cubre Gold Coast, Brisbane y otros estados.',
  },
  {
    id: 'rec_017',
    nombre: 'WorkCon Gold Coast',
    email: '',
    direccion: '7/10 Green Glen Rd, Ashmore QLD 4214',
    barrio: 'Ashmore',
    lat: -28.0150,
    lng: 153.3720,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Labour hire especializado en construccion, infraestructura y control de trafico. ABN: 80 639 664 949. QBCC #15216299. Tel: 07 3558 0660.',
  },
  {
    id: 'rec_018',
    nombre: 'Your Trades Gold Coast',
    email: '',
    direccion: 'Level 1, 66 Marine Parade, Southport QLD 4215',
    barrio: 'Southport',
    lat: -27.9708,
    lng: 153.4167,
    status: 'Pendiente',
    emailVerified: null,
    hidden: false,
    notas: 'Blue-collar recruitment. Construccion, obras civiles, renovables. Tel: 1300 160 215. QLD-based.',
  },
  {
    id: 'rec_019',
    nombre: 'APM Employment Services Gold Coast',
    email: 'apm4jobs@apm.net.au',
    direccion: 'Gold Coast QLD (multiples ubicaciones)',
    barrio: 'Gold Coast',
    lat: -28.0023,
    lng: 153.4145,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Workforce Australia, Inclusive Employment Australia, Apprenticeships. Empleo inclusivo, soporte a trabajadores con discapacidad y job seekers. Tel: 1800 276 276. General: support@apm.net.au.',
  },
  {
    id: 'rec_014',
    nombre: 'JPS Recruitment',
    email: 'construction@jpsrecruit.com.au',
    direccion: 'Level 8, 179 Turbot Street, Brisbane QLD 4000',
    barrio: 'Brisbane CBD',
    lat: -27.4671,
    lng: 153.0214,
    status: 'Pendiente',
    emailVerified: true,
    hidden: false,
    notas: 'Especialistas en construccion, mineria y ventas. Atiende Brisbane y Gold Coast. Tel: 07 2000 5560. Tambien: mining@jpsrecruit.com.au',
  },
];
